name: 'Auto-Create Release Pull Requests'
on:
  push:
    branches:
      - develop
jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: 
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: trunk
          title: "chore(bot): next release"
          body: "**Automated pull request**"
          assignee: ${{ github.actor }}
          label: automatic, next-release
          template: .github/PULL_REQUEST_TEMPLATE.md
          get_diff: true
