name: 'Tag and Release'

on:
  push:
    branches:
      - trunk

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - name: Install NPM Dependencies
        run: npm install
      
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release
